### ISSUE TITLE
element-desktop (Matrix reference client)

### ISSUE THREAD

**Issue by SierraKiloBravo** [rpmfusion-infra/fedy#102]
Summary: Element is the reference client for the Matrix federated messaging platform. 
URL: https://github.com/vector-im/element-web/
Why not in Fedora: Indirect dependency (via Electron) on ffmpeg.
Notes: taw00 has provided a COPR repository @ https://copr.fedorainfracloud.org/coprs/taw/element/ https://github.com/taw00/element-rpm/ but was barred from publishing builds for aforementioned reason.

**Comment by orowith2os** [comment]
Going to comment on this, as I've actually looked at this in the past: Why package Element, when a (seemingly fine) flatpak package already exists? I don't really see much reason to package a native package of Element for this reason.

If there's some functionality missing, or an issue with the flatpak that doesn't exist on the native package, please do tell me, I'm open to criticism.

**Comment by kwizart** [comment]
Note that there is already a native element package in obs://build.opensuse.org/home:jejb1

**Comment by kwizart** [comment]
Will be fixed in the next release:
https://github.com/rpmfusion-infra/fedy/commit/0b751ac7fe44baf8aaeac35f1691a227c5328191
