### ISSUE TITLE
R8168 Realtek driver

### ISSUE THREAD

**Issue by mdombrovsky** [rpmfusion-infra/fedy#103]
** Please describe why this package is not eligible for Fedora ?**
Please mention why Fedora cannot package this component and which RPM Fusion section would apply "free, nonfree, rpi, cuda".
Fedora already includes R8169 realtek driver which is broken (Ethernet does not work).

** Is this software redistributable ?**
If a proprietary software is there a notice that the component can be redistributed ?
The software seems to use GPL-2.0 license.

** Is this software an alternate version of a Fedora provided package ?**
If the package already exists in Fedora, please mention why it is incomplete and if the fedora package is even relevant ?
Yes, its like the R8169 driver in Fedora, but it actually works.

**Additional context**
The software is available from here: https://github.com/mtorromeo/r8168

**Comment by leigh123linux** [comment]
Duplicate #91
