### ISSUE TITLE
Add support for Git commands in color prompt.

### ISSUE THREAD

**Issue by gregharvey** [rpmfusion-infra/fedy#106]
Every time I get a new computer I end up putting my `git` command line prompts back in. I actually think they're pretty nice (I didn't make them, I've left comments in place in the PR to credit original developer) as they show at a glance if the Git repo you're in has changes to commit, as well as the branch you're on - it also appears "normally" if you're not in a Git repo, so doesn't impact user experience in a normal directory.

**Describe the solution you'd like**
Have a look at the PR: https://github.com/rpmfusion-infra/fedy/pull/105

I've opted to make it a separate item, but if you thought there's no need I can repackage this to simply add the Git options directly to Color Prompt.

**Additional context**
Here's an example in a repo, I'm in the `main` branch and there are changes, hence the `*` - you can also see when I `cd` out of the directory I have a "normal" command prompt:

![image](https://user-images.githubusercontent.com/238550/175531014-8ae37e31-174b-4846-8e49-211a30c6da2a.png)

**Comment by kwizart** [comment]
I'm using powerline for this myslef, which is a dedicated project (available in fedora)

So I find it a little use to have everyone custom git script added, it's unlikely that it will fit for scale usage...

**Comment by kwizart** [comment]
No answer about using powerline instead , which is a better established project.

**Comment by gregharvey** [comment]
Powerline looks nice, I'll try it next time I do a clean install of a machine.
