### ISSUE TITLE
VirtualBox package with Guest Additions

### ISSUE THREAD

**Issue by pguerin3** [rpmfusion-infra/fedy#108]
** Please describe why this package is not eligible for Fedora ?**
Presently the VirtualBox package is included in RPM Fusion.
https://muug.ca/mirror/rpmfusion/free/fedora/releases/35/Everything/x86_64/os/repoview/VirtualBox.html
However, the RPM Fusion package does not include the VBoxGuestAdditions.iso file.

The appropriate Oracle Virtualbox package for Fedora 36, Fedora 35, Fedora 33 / 34, and Fedora 32 does have the VBoxGuestAdditions.iso.
https://www.virtualbox.org/wiki/Linux_Downloads

Now, I could simply obtain the VBoxGuestAdditions.iso by downloading the Oracle Virtualbox package for Fedora, and following the instructions to install it in a virtual machine.
But if I need to download the Oracle Virtualbox package for Fedora to get the VBoxGuestAdditions.iso, then what is the point of using the RPM Fusion package?
Is there any point having the RPM Fusion package for Virtualbox, if I need to download the Oracle Virtualbox package for Fedora anyway?

** Is this software redistributable ?**
I'm not aware of the VBoxGuestAdditions.iso having a different distribution policy than for VirtualBox.

** Is this software an alternate version of a Fedora provided package ?**
I argue that if the VirtualBox package in RPM Fusion is not made complete by including the VBoxGuestAdditions.iso file, then there is little point having the VirtualBox package in RPM Fusion at all.

**Comment by leigh123linux** [comment]
Fedora provides virtualbox-guest-additions



[<br class="Apple-interchange-newline">](https://koji.fedoraproject.org/koji/packageinfo?packageID=26262)
