### ISSUE TITLE
Tweaks, Better Font Rendering - did not install

### ISSUE THREAD

**Issue by goxaxa** [rpmfusion-infra/fedy#11]
**Describe the bug**
The "Better Font Rendering" option in Tweaks did not install.

**To Reproduce**
run fedy
select Tweaks
select Better Font Rendering

The terminal window displays the error :
No match for argument: fedy-font-config
Error: Unable to find a match: fedy-font-config

**Expected behavior**
Better Font Rendering should install.

**Screenshots**

**Version Information:**
Please run the following commands in the terminal and provide the output after the colon:
- `rpm -qi fedy`:
Name        : fedy
Version     : 5.0.0
Release     : 1.fc31
Architecture: noarch
Install Date: Tue 19 Nov 2019 23:13:59 AWST
Group       : System/Management
Size        : 271461
License     : GPLv3+
Signature   : RSA/SHA1, Wed 04 Sep 2019 00:07:42 AWST, Key ID c27efd7a2da862e5
Source RPM  : fedy-5.0.0-1.fc31.src.rpm
Build Date  : Wed 04 Sep 2019 00:07:37 AWST
Build Host  : copr-builder-764540827.novalocal
URL         : https://github.com/rpmfusion-infra/fedy-project
Summary     : Install codecs and additional software
Description :
Fedy lets you install multimedia codecs and additional software that Fedora
doesn't want to ship, like mp3 support, Adobe Flash, Oracle Java etc., and
much more with just a few clicks.

- `rpm -E %fedora`: 31

- `uname -a`: Linux pc 5.3.7-301.fc31.x86_64 #1 SMP Mon Oct 21 19:18:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by kwizart** [comment]
The better Font Rendering is totally obsolete freetype-freeworld is now removed from rpmfusion and the related features are enabled in the fedora side.

**Comment by kwizart** [comment]
Removed in fedy

**Comment by kwizart** [comment]
Fixed in 5.0.1 now in repos.
Thx for the report.
