### ISSUE TITLE
Split the steam package into steam and steam-devices

### ISSUE THREAD

**Issue by orowith2os** [rpmfusion-infra/fedy#112]
** Is this software redistributable ?**
Steam-devices is distributable under the terms of the MIT license.

**Additional context**
Silverblue users may not want to install the whole Steam package from rpmfusion, as they can use the flatpak, or use it inside of a container. Steam-devices is only required for some udev rules to ensure that Steam functions properly. Splitting the Steam package into two separate packages can help Silverblue users, and Workstation users that don't want to install the native package of Steam.

**Comment by orowith2os** [comment]
> There is already a steam-devices package, so I'm not sure what do you mean by this request ?

Using the admin.rpmfusion.org/pkgdb page, I only see Steam when searching for it, no steam-devices: https://admin.rpmfusion.org/pkgdb/package/nonfree/steam/

**Comment by leigh123linux** [comment]
sub-packages aren't listed at pkgdb.
