### ISSUE TITLE
Openshot-qt version 3.0.0

### ISSUE THREAD

**Issue by gitbrasser** [rpmfusion-infra/fedy#113]
** Please describe why this package is not eligible for Fedora ?**
I don't know. But the current version (2.6.1-dev) is in the rpmfusion-free-updates repository.

** Is this software redistributable ?**
Yes

** Is this software an alternate version of a Fedora provided package ?**
No

**Additional context**
The current version in the repository contains a bug that is solved in 3.0.0.

**Comment by leigh123linux** [comment]
https://rpmfusion.ip-connect.info/free/fedora/updates/36/x86_64/repoview/openshot.html

**Comment by gitbrasser** [comment]
> https://rpmfusion.ip-connect.info/free/fedora/updates/36/x86_64/repoview/openshot.html

I should have asked for F35 of course ;-) But then the best reply would be.. 'upgrade your Fedora'...
