### ISSUE TITLE
Package wishlist: zoom

### ISSUE THREAD

**Issue by paul9115** [rpmfusion-infra/fedy#115]
** Please describe why this package is not eligible for Fedora ?**
non-free propriety software 

** Is this software redistributable ?**
There is no notice that the software cannot be redistributed, although I wasn't able to find anything explicitly permitting it, it is also available as a flatpack so I would assume it will be OK. 

** Is this software an alternate version of a Fedora provided package ?**
No 

**Additional context**
Request pertains to the desktop client for zoom, found here https://zoom.us/download?os=linux

**Comment by kwizart** [comment]
Zoom package installation is already supported by fedy. Why this request ?

**Comment by leigh123linux** [comment]
-1 to this request,  I consider zoom as Chinese spyware.
