### ISSUE TITLE
[RHEL] Mesa with removed codecs (h264, h265, vc1)

### ISSUE THREAD

**Issue by cyqsimon** [rpmfusion-infra/fedy#121]
**Please describe why this package is not eligible for Fedora ?**
Same as #110. See also [this reddit post](https://www.reddit.com/r/Fedora/comments/13jxszs/rhel_92_they_took_our_h264h265_mesa_gpu/).

**Is this software redistributable ?**
Yes.

**Is this software an alternate version of a Fedora provided package ?**
Yes.

**Additional context**
- It seems like the retroactive removal applies to all supported versions of RHEL (7-9), not just RHEL9.
- `mesa-dri-drivers` (still used in RHEL7-9) is the old package name for `mesa-va-drivers` (used in Fedora). The package contents are unchanged.

**Comment by kwizart** [comment]
We can easily complement this package or we would need to fully replace mesa-dri-drivers.

Use  Fedora  for desktop !

**Comment by kwizart** [comment]
re-open since the implementation detail doesn't remove the need.

**Comment by cyqsimon** [comment]
> Use Fedora for desktop !

For context, there are plenty of legitimate uses for hardware accelerated graphics on a server. The one that prompted me to submit this issue is [decoding camera streams in Frigate NVR](https://docs.frigate.video/configuration/hardware_acceleration#amdati-gpus-radeon-hd-2000-and-newer-gpus-via-libva-mesa-driver). The application is containerised, but I think it still needs support from Mesa installed on host.

**Comment by kwizart** [comment]
use fedora on such servers.

Or via containers.. some times ago I've tried to maintain https://hub.docker.com/r/rpmfusion/ffmpeg
But it won't have newer mesa-freeworld counterparts...
