### ISSUE TITLE
Could not install almost all themes

### ISSUE THREAD

**Issue by Tymisko** [rpmfusion-infra/fedy#123]
**Describe the bug**
Could not install 
- Adapta Theme
- Arc Icon Theme
- Arc Theme
- EvoPop themes
- Flat-Remix Theme

Only **Moka Icon Theme**, **Papirus icon theme** and **Numix themes** was successfully installed.

**To Reproduce**
1. Open Terminal
2. Type in `Fedy`
3. Open Themes tab
4. Click install Adapta Theme
5. Type in password if asked for
6. Adapta Theme (Install) failed.

**Expected behavior**
Adapta Theme is successfully installed.

**Screenshots**
![image](https://github.com/rpmfusion-infra/fedy/assets/43744496/2443e30c-897e-4f54-b8d0-db536aba8a89)

**Version Information:**
Please run the following commands in the terminal and provide the output after the colon:
- `rpm -qi fedy`:
```
Name        : fedy
Version     : 5.0.30
Release     : 1.fc38
Architecture: noarch
Install Date: Sun 17 Sep 2023 06:46:21 AM EDT
Group       : Unspecified
Size        : 518468
License     : GPLv3+
Signature   : RSA/SHA256, Sat 20 May 2023 12:43:23 AM EDT, Key ID c27efd7a2da862e5
Source RPM  : fedy-5.0.30-1.fc38.src.rpm
Build Date  : Sat 20 May 2023 12:43:18 AM EDT
Build Host  : copr-hv-x86-64-01-prod-02511603-20230520-041937
Vendor      : Fedora Copr - user kwizart
URL         : https://github.com/rpmfusion-infra/fedy
Summary     : Install codecs and additional software
Description :
Fedy lets you install multimedia codecs and additional software that Fedora
doesn't want to ship, like mp3 support, Adobe Flash, Oracle Java etc., and
much more with just a few clicks
```
- `rpm -E %fedora`: 38
- `uname -a`: Linux fedora 6.2.9-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 22:32:58 UTC 2023 x86_64 GNU/Linux

**Additional context**
```
Last metadata expiration check: 0:01:50 ago on Sun 17 Sep 2023 07:03:33 AM EDT.
No match for argument: adapta-gtk-theme
Error: Unable to find a match: adapta-gtk-theme
```

**Comment by Tymisko** [comment]
Why you want to remove it instead fix it? I don't get it. Is this software being abandoned?

**Comment by kwizart** [comment]
I'm not the maintainer of the said themes. So I won't dedicate time to sort out what needs fix.
If they can't be installed, they will be removed from fedy.
