### ISSUE TITLE
Update brave install script according to official documentation

### ISSUE THREAD

**Issue by Tymisko** [rpmfusion-infra/fedy#124]
**Is your feature request related to a problem? Please describe.**
Your brave install.sh script is 4 years old. 

**Describe the solution you'd like**
Please update [`install.sh`](https://github.com/rpmfusion-infra/fedy/blob/master/plugins/brave.plugin/install.sh) script located in the plugins/brave according to the instructions from the official brave site.
https://brave.com/linux/

**Describe alternatives you've considered**
Not applicable

**Additional context**
Not applicable

**Comment by kwizart** [comment]
Sorry but what do you want to change very exactly ?
Can you provide an diff patch (as a MR if possible).
