### ISSUE TITLE
Package Wishlist: Advanced Media Framework (AMF)

### ISSUE THREAD

**Issue by KayJay7** [rpmfusion-infra/fedy#137]
**Please describe why this package is not eligible for Fedora?**
It includes encoders/decoders for patent encumbered media codecs. e.g.: h.264, h.265

**Is this software redistributable?**
The software itself has an opensource library, developed and maintained by AMD as part of GPUOpen. The source is available at https://github.com/GPUOpen-LibrariesAndSDKs/AMF

**Additional context**
AMF is AMD's most featureful media encoding/decoding framework. It has always required the proprietary `AMDVLK-PRO` driver, but the latest version has experimental support for `RADV` so it can be packaged on it's own and used without AMD's proprietary drivers.
Moreover, AMD has recently submitted [patches](https://patchwork.ffmpeg.org/project/ffmpeg/patch/20240501183809.1060-1-ovchinnikov.dmitrii@gmail.com/) to include AMF support in `ffmpeg` upstream.
Currently AMD provides installers for SLE, RHEL, and Ubuntu.

**Comment by leigh123linux** [comment]
AMF is already included in fedora https://koji.fedoraproject.org/koji/packageinfo?packageID=35242

**Comment by KayJay7** [comment]
That package is only a src.rpm and cannot be installed by dnf

**Comment by leigh123linux** [comment]
```
$ sudo dnf info AMF*
Last metadata expiration check: 3:33:34 ago on Sun 12 May 2024 07:40:09 BST.
Available Packages
Name         : AMF-devel
Version      : 1.4.33
Release      : 1.fc40
Architecture : noarch
Size         : 2.8 M
Source       : AMF-1.4.33-1.fc40.src.rpm
Repository   : fedora
Summary      : Development files for AMF
URL          : https://gpuopen.com/advanced-media-framework/
License      : MIT
Description  : A light-weight, portable multimedia framework that abstracts away most of the
             : platform and API-specific details. AMF is supported on the closed source AMD
             : Pro driver and OpenMax on the open source AMD Mesa driver.
             : 
             : The AMF-devel package contains libraries and header files for developing
             : applications that use AMF.

Name         : AMF-samples
Version      : 1.4.33
Release      : 1.fc40
Architecture : noarch
Size         : 745 k
Source       : AMF-1.4.33-1.fc40.src.rpm
Repository   : fedora
Summary      : Sample files for AMF
URL          : https://gpuopen.com/advanced-media-framework/
License      : MIT
Description  : The AMF-samples package contains sample programs and source for applications
             : that use AMF.
```

**Comment by leigh123linux** [comment]
> That package is only a src.rpm and cannot be installed by dnf.
> 
> Correction: after building it, it does not include the AMF runtime, but just header files (in the AMF-devel) and samples (in AMF-samples)

Isn't the runtime stuff provided by the closed source AMD driver packages which only support RHEL, Debian and Ubuntu

**Comment by KayJay7** [comment]
It is provided by the proprietary driver, but the installer that only supports rhel also allows to install AMF alone (according to the [docs](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/wiki/Driver%20Linux)). I thought the runtime itself wasn't part of the proprietary driver but just provided with it. I also thought the runtime itself was opensource or at least redistributable, partly because they want it to run on RADV.

**Comment by leigh123linux** [comment]
> It is provided by the proprietary driver, but the installer that only supports rhel also allows to install AMF alone (according to the [docs](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/wiki/Driver%20Linux)). I thought the runtime itself wasn't part of the proprietary driver but just provided with it. I also thought the runtime itself was opensource or at least redistributable, partly because they want it to run on RADV.

To qualify as open source the un-compiled source code must be publicly available, can you find it?

**Comment by KayJay7** [comment]
I cannot, I thought the source was found at [GPUOpen-LibrariesAndSDKs/AMF](https://github.com/GPUOpen-LibrariesAndSDKs/AMF) but that is just the sdk.
