### ISSUE TITLE
MS TrueTypes Core Fonts Install fails

### ISSUE THREAD

**Issue by Xmetalfanx** [rpmfusion-infra/fedy#138]
**Describe the bug**
When installing the MS Truetype Core fonts it fails 

**To Reproduce**
Go to the Utilities Panel/Window/whatever and hit install in MS Truetype core fonts in Fedora 40 (my test Fedora version) 

**Expected behavior**
for MS fonts to install 

**Screenshots**

**Version Information:**
Please run the following commands in the terminal and provide the output after the colon:
- `rpm -qi fedy`:
Name        : fedy
Version     : 5.0.44
Release     : 1.fc40
Architecture: noarch
Install Date: Fri 17 May 2024 03:31:33 PM EDT
Group       : Unspecified
Size        : 520241
License     : GPLv3+
Signature   : RSA/SHA256, Fri 17 May 2024 08:27:03 AM EDT, Key ID c27efd7a2da862e5
Source RPM  : fedy-5.0.44-1.fc40.src.rpm
Build Date  : Fri 17 May 2024 08:26:56 AM EDT
Build Host  : copr-hv-x86-64-02-prod-07046473-20240517-122238
Vendor      : Fedora Copr - user kwizart
URL         : https://github.com/rpmfusion-infra/fedy
Summary     : Install codecs and additional software
Description :
Fedy lets you install multimedia codecs and additional software that Fedora
doesn't want to ship, like AAC,H264,H265 support, pre-built software, and
much more with just a few clicks.
- `rpm -E %fedora`:
   40 
- `uname -a`:
	 Linux fedora 6.8.9-300.fc40.x86_64  SMP PREEMPT_DYNAMIC Thu May  2 18:59:06 UTC 2024 x86_64 GNU/Linux
 	

**Additional context**
At least in Fedora 40, the used package seems to have been removed

**Comment by leigh123linux** [comment]
File the issue at rpmfusion bugzilla so the maintainer can investigate.

https://bugzilla.rpmfusion.org/enter_bug.cgi

https://github.com/rpmfusion-infra/fedy/blob/5221014190cc7f05c89eca47447aa570f05af686/plugins/msttcorefonts.plugin/install.sh#L3

https://mirror.netsite.dk/rpmfusion/nonfree/fedora/releases/40/Everything/x86_64/os/repoview/lpf-mscore-fonts.html
