### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by MalteKiefer** [rpmfusion-infra/fedy#23]
Hi,

Could you please push a new version to the repo.
Lots of changes since the last version.
Thanks

**Comment by kwizart** [comment]
Yep, I'm sort of out of work now.
Let's schedule this for Monday (I will have to push few things on my side also).

Hopefully it should only be a matter to update the changelog, bump spec release and create a new tag. With copr wired to this github everything should be built automatically...

**Comment by MalteKiefer** [comment]
OK then I can add some new plugins
Have some on my list

Am 28. Dezember 2019 11:09:35 MEZ schrieb "Nicolas Chauvet (kwizart)" <notifications@github.com>:
>Yep, I'm sort of out of work now.
>Let's schedule this for Monday (I will have to push few things on my
>side also).
>
>Hopefully it should only be a matter to update the changelog, bump spec
>release and create a new tag. With copr wired to this github everything
>should be built automatically...
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rpmfusion-infra/fedy/issues/23#issuecomment-569403988

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by kwizart** [comment]
Is there any remaining plugin to add before the tag ?

**Comment by MalteKiefer** [comment]
No didn't find the time.
Sorry

Am 1. Januar 2020 18:31:33 MEZ schrieb "Nicolas Chauvet (kwizart)" <notifications@github.com>:
>Is there any remaining plugin to add before the tag ?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rpmfusion-infra/fedy/issues/23#issuecomment-570069741
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by kwizart** [comment]
No problem, feel free to report any issue, fedy 5.0.2 is currently building with copr)
(I only had to push a new tag, was so easy).

Thx for your report and PRs

**Comment by MalteKiefer** [comment]
Thanks.
You are welcome 

Am 1. Januar 2020 19:05:03 MEZ schrieb "Nicolas Chauvet (kwizart)" <notifications@github.com>:
>Closed #23.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rpmfusion-infra/fedy/issues/23#event-2916638625
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
