### ISSUE TITLE
Can't access repo https://dl.folkswithhats.org/fedora/30/

### ISSUE THREAD

**Issue by nitipit** [rpmfusion-infra/fedy#5]
**Describe the bug**
Can't access repo https://dl.folkswithhats.org/fedora/30/

**Comment by leigh123linux** [comment]
That site isn't anything to do with rpmfusion, the original fedy author deleted his repo.

**Comment by kwizart** [comment]
We might need to handle the transition to the new site.
One idea is to use the kwizart/fedy copr repo generate fedy packages
Then it might be possible to use the rpmfusion obsolete package to obsolete/remove the fedy-release...
