### ISSUE TITLE
Make available to RHEL 8

### ISSUE THREAD

**Issue by befields** [rpmfusion-infra/fedy#53]
When trying to install fedy on rhel8, the repo comes back as unable to download metadata and also nothing to build int his repo.

**Comment by kwizart** [comment]
It will be some amount of work to verify that which components are available in EL8 (either CentOS RHEL or derivates), and guards as appropriate.

But that's something that can be looked into.
Although it will be at any contributor pace.

You can probably try to build or install fedy by hand and try to verify if it works for you...

**Comment by kwizart** [comment]
Fedy 5.0.9 is available for epel8, but it totally "untested."

Please report PR with Fixes, not only issue
