### ISSUE TITLE
Peazip installation fails

### ISSUE THREAD

**Issue by julroy67** [rpmfusion-infra/fedy#54]
**Describe the bug**
Peazip installation fails. Trying to enable the brollylssj/PeaZip, dnf says there is no executable so the copr repo cannot be used.

**To Reproduce**
1. Go to Apps
2. Scroll down to Peazip
3. Click on install

**Expected behavior**
Peazip should get installed.

**Version Information:**
Please run the following commands in the terminal and provide the output after the colon:
- `rpm -qi fedy`:

> Name        : fedy
> Version     : 5.0.6.2
> Release     : 1.fc31
> Architecture: noarch
> Install Date: mar. 04 févr. 2020 23:11:23 JST
> Group       : Unspecified
> Size        : 499151
> License     : GPLv3+
> Signature   : RSA/SHA1, lun. 03 févr. 2020 19:13:16 JST, Key ID c27efd7a2da862e5
> Source RPM  : fedy-5.0.6.2-1.fc31.src.rpm
> Build Date  : lun. 03 févr. 2020 19:13:10 JST
> Build Host  : ip-172-30-2-33.ec2.internal
> URL         : https://github.com/rpmfusion-infra/fedy
> Summary     : Install codecs and additional software
> Description :
> Fedy lets you install multimedia codecs and additional software that Fedora
> doesn't want to ship, like mp3 support, Adobe Flash, Oracle Java etc., and
> much more with just a few clicks.

- `rpm -E %fedora`: 31

- `uname -a`: Linux initia 5.4.19-200.fc31.x86_64 #1 SMP Wed Feb 12 15:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kwizart** [comment]
If you can't contribute a fix, this plugin will be removed...

**Comment by leigh123linux** [comment]
It needs to be removed as there is no f31 support for peazip.

https://copr.fedorainfracloud.org/coprs/brollylssj/PeaZip/
