### ISSUE TITLE
Unable to remove/uninstall Watchman. Fedy reports Task failed!

### ISSUE THREAD

**Issue by karansapolia** [rpmfusion-infra/fedy#58]
**Describe the bug**
I installed Watchman using Fedy, now I am unable to remove/uninstall Watchman. Fedy fails to uninstall and doesn't show any reason. Running any watchman command throws the same error. Stuck.

**To Reproduce**
1. Go to Fedy
2. Click on Remove button next to Watchman (if you have it installed).
4. See error (happens in my case)

**Expected behavior**
1. Watchman should get removed successfully when Remove is clicked.

**Screenshots**
![Screenshot_20200504_210339](https://user-images.githubusercontent.com/10175625/80984520-98795000-8e4b-11ea-82ae-eb11da0a8c1f.png)
![Screenshot_20200504_210421](https://user-images.githubusercontent.com/10175625/80984536-9ca56d80-8e4b-11ea-8ffb-b45be79b58ab.png)

**Version Information:**
Please run the following commands in the terminal and provide the output after the colon:
- `rpm -qi fedy`: 
```
$ rpm -qi fedy
Name        : fedy
Version     : 5.0.6.2
Release     : 1.fc31
Architecture: noarch
Install Date: Mon 04 May 2020 08:44:26 PM IST
Group       : Unspecified
Size        : 499151
License     : GPLv3+
Signature   : RSA/SHA1, Mon 03 Feb 2020 03:43:16 PM IST, Key ID c27efd7a2da862e5
Source RPM  : fedy-5.0.6.2-1.fc31.src.rpm
Build Date  : Mon 03 Feb 2020 03:43:10 PM IST
Build Host  : ip-172-30-2-33.ec2.internal
URL         : https://github.com/rpmfusion-infra/fedy
Summary     : Install codecs and additional software
Description :
Fedy lets you install multimedia codecs and additional software that Fedora
doesn't want to ship, like mp3 support, Adobe Flash, Oracle Java etc., and
much more with just a few clicks.
```

- `rpm -E %fedora`:
```
$ rpm -E %fedora
31
```
- `uname -a`:
```
$ uname -a
Linux localhost.localdomain 5.6.8-200.fc31.x86_64 #1 SMP Wed Apr 29 19:10:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**
Running any watchman command throws the same error:
```
$ watchman shutdown-server
2020-05-04T21:13:00,822: [] while computing sockname: failed to create /usr/var/run/watchman/x-state: No such file or directory
```
```
$ watchman watch
2020-05-04T21:13:51,153: [] while computing sockname: failed to create /usr/var/run/watchman/x-state: No such file or directory
```

**Comment by kwizart** [comment]
If there is no better version than the eklitzke/watchman copr repo, I'm afraid this component will have to be removed...

**Comment by karansapolia** [comment]
For now, how do I understand what is the error and how do I uninstall Watchman? I need to reinstall it for work.

**Comment by kwizart** [comment]
I don't know, It's not my fault if it's unmaintained by the maintainer.

**Comment by karansapolia** [comment]
Was able to uninstall it using dnf though. Would be great if we have an up to date way of installing/uninstalling it through Fedy. Let me know what the process might be if we need an updated copr for it. Would be happy to maintain it.

**Comment by kwizart** [comment]
You can have a look at the fedy plugin from /usr/share/fedy and see what is done.
copr is https://copr.fedorainfracloud.org/

I plan to push a new fedy release soon, so I'm going to remove this plugin. Please resubmit a new one if there is a maintained version.

**Comment by kwizart** [comment]
Plugin removed, feel free to submit a new one if any copr repos is working.
