### ISSUE TITLE
Fedy 5.0.0 segfaults in gdk_surface_get_display on Fedora 31

### ISSUE THREAD

**Issue by thestonewell** [rpmfusion-infra/fedy#6]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: simply launch fedy then it crashes with a seg fault

```
Gjs-Message: 09:40:49.830: JS WARNING: [./app.js 6]: Requiring Gtk but it has 3 versions available; use imports.gi.versions to pick one
Failed to load application icon: this._window.set_icon is not a function

(gjs:9884): Gjs-WARNING **: 09:40:49.915: JS ERROR: Error: No property show_close_button on GtkHeaderBar
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/overrides/Gtk.js:63:9
_buildUI@./app.js:49:27
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_onStartup@./app.js:76:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
@./app.js:720:1


(gjs:9884): Gdk-CRITICAL **: 09:40:49.916: gdk_surface_get_display: assertion 'GDK_IS_SURFACE (surface)' failed
/usr/share/fedy/fedy: line 3:  9884 Segmentation fault      (core dumped) ./app.js $@

```
**Expected behavior**
it starts :)

**Version Information:**
- `rpm -qi fedy`:
Name        : fedy
Version     : 5.0.0
Release     : 1.fc31
Architecture: noarch
Install Date: Sun Nov 10 09:31:33 2019
Group       : System/Management
Size        : 271461
License     : GPLv3+
Signature   : RSA/SHA1, Tue Sep  3 18:07:42 2019, Key ID c27efd7a2da862e5
Source RPM  : fedy-5.0.0-1.fc31.src.rpm
Build Date  : Tue Sep  3 18:07:37 2019
Build Host  : copr-builder-764540827.novalocal
URL         : https://github.com/rpmfusion-infra/fedy-project

- `rpm -E %fedora`:
31
- `uname -a`:
Linux gucky 5.3.8-300.fc31.x86_64 #1 SMP Tue Oct 29 14:28:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thestonewell** [comment]
Based on the first WARNING maybe the code has to be adjusted according to:
https://developer.gnome.org/platform-overview/unstable/tour-gjs.html.en

```
imports.gi.versions.Gtk = '3.0';
const Gtk = imports.gi.Gtk;
```

**Comment by thestonewell** [comment]
based on above the following code changes made it work for me again:
```
diff --git a/app.js b/app.js
index 1d10e91..e18eaa6 100755
--- a/app.js
+++ b/app.js
@@ -1,6 +1,8 @@
 #!/usr/bin/gjs
 
 imports.searchPath.unshift('.');
+// force GTK 3
+imports.gi.versions.Gtk = '3.0';
 const Gio = imports.gi.Gio;
 const GLib = imports.gi.GLib;
 const Gtk = imports.gi.Gtk;
```

**Comment by kwizart** [comment]
Thx for the report.
Can you submit a PR
Is this work with at least fedora 30 also ?

**Comment by thestonewell** [comment]
I can no longer test fc30 but since fc30 just had GTK3 I'd assume so.

Will figure out the PR but might take a while. Sorry, not fluent (yet) on PRs

**Comment by leigh123linux** [comment]
> Is this work with at least fedora 30 also ?

This will work with any distro that has gtk3 available.

**Comment by thestonewell** [comment]
PR at https://github.com/rpmfusion-infra/fedy/pull/7
