### ISSUE TITLE
Master PDF Editor completely broken for Fedora 32

### ISSUE THREAD

**Issue by gregharvey** [rpmfusion-infra/fedy#61]
**Describe the bug**
If you install Master PDF Editor with Fedy on Fedora 32 there are multiple issues. Firstly, the installer grabs this file:
https://code-industry.net/public/master-pdf-editor-5.4.38-qt5.x86_64.rpm

Unfortunately this RPM is no longer valid for Fedora 32, you need the tar.gz version for Qt 5.9.8 or later, which is not available on their website as an RPM. Here's the output for Qt5 version on Fedora 32:

```
$ qmake-qt5 --version
QMake version 3.1
Using Qt version 5.14.2 in /usr/lib64
```

So this is the correct version to download, at time of writing:
https://code-industry.net/public/master-pdf-editor-5.4.38-qt5-all.amd64.tar.gz

*However*, even if you grab that it won't run, there's a `'Qt_5_PRIVATE_API' not found` error and this Fedora bug report, while a couple of years old, probably explains why:
https://bugzilla.redhat.com/show_bug.cgi?id=1595089#c1

It doesn't sound like there's a simple solution to this. I tried a few suggested workarounds for similar issues with people running other applications, but nothing seems to work. It's probably a case of removing this for Fedora 32, for now, and raising it with the Master PDF Editor devs. :-(

**To Reproduce**
1. Install Master PDF Editor on a clean Fedora 32 via Fedy
2. Open a client and run `/opt/master-pdf-editor-5/master-pdf-editor-5`
3. See error

**Expected behavior**
Master PDF Editor runs. ;-)

**Version Information:**
Please run the following commands in the terminal and provide the output after the colon:
- `rpm -qi fedy`:

```
Name        : fedy
Version     : 5.0.9
Release     : 1.fc32
Architecture: noarch
Install Date: Tue 19 May 2020 17:13:46 CEST
Group       : Unspecified
Size        : 503274
License     : GPLv3+
Signature   : RSA/SHA1, Sun 17 May 2020 11:12:10 CEST, Key ID c27efd7a2da862e5
Source RPM  : fedy-5.0.9-1.fc32.src.rpm
Build Date  : Sun 17 May 2020 11:12:07 CEST
Build Host  : ip-172-30-2-190.ec2.internal
URL         : https://github.com/rpmfusion-infra/fedy
Summary     : Install codecs and additional software
Description :
Fedy lets you install multimedia codecs and additional software that Fedora
doesn't want to ship, like mp3 support, Adobe Flash, Oracle Java etc., and
much more with just a few clicks.
```

- `rpm -E %fedora`:

`32`

- `uname -a`:

`Linux greg-x390-codeenigma-net 5.6.18-300.fc32.x86_64 #1 SMP Wed Jun 10 21:38:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by gregharvey** [comment]
I don't know if this makes a difference, but I've heard back from the devs. The Qt5 libraries are bundled but you can't launch with the binary, you need to use the shell script. I've tried this and it seems to work. So the installation script would need to:

1. Grab the tar.gz and extract it
2. Copy the .desktop file to the right place (it already calls the shell script on the Exec line)

But it should be doable, just not as simple as it was.

**Comment by kwizart** [comment]
Feel free to modify the older plugin and submit a working/tested version as a PR.

That been said:
- Its more difficult to maintain a plugin without a working RPM package (or even a yum/dnf repository  to get upgraded packages).
- Upstream bundling qt5 instead of using a system version is less easier to maintain and hit bugs related to the bundled qt5.
- Upstream using qt5 private symbols  make it unlikely to rely on a system qt5 version...

**Comment by pizzadude** [comment]
There's a flatpak of Master PDF Editor which works...

https://flathub.org/apps/details/net.codeindustry.MasterPDFEditor

**Comment by gregharvey** [comment]
Sounds like it's not worth it, indeed. It would be a pita to maintain. Never mind, if they ever package an RPM that works for Fedora again and I remember I'll come back and make a PR that works. Otherwise, not the end of the world. Thanks for replying! :-)
