### ISSUE TITLE
Get `arc-theme` to pull from Copr mhdahmad/workstation.

### ISSUE THREAD

**Issue by ghost** [rpmfusion-infra/fedy#64]
The current pulled theme is very borked on the latest GNOME, and unmaintained.

**Comment by kwizart** [comment]
Can you submit a pull request to switch the copr provider or remove the theme ?

**Comment by NickAvem** [comment]
> Can you submit a pull request to switch the copr provider or remove the theme ?

Will do! Building and testing rn.

**Comment by leigh123linux** [comment]
I am -1 to adding this to fedy

1. We have a non-replacement policy, we don't replace fedora provided packages

https://koji.fedoraproject.org/koji/buildinfo?buildID=1321290

2. This theme is too broken to ship.

**Comment by kwizart** [comment]
@NickAvem  have you try to contact the copr maintainer so it can take-over the original fedora package ?
Is there any PR on pagure to review the package change from copr ?

QOL ?

**Comment by NickAvem** [comment]
Quality of life. 

I don't know the maintainer, but I think I have the GitHub of a guy who does. When I finish up my work I'll look into it.

**Comment by kwizart** [comment]
Any news on this topic ?

arc-theme have seen updates, but are they provided by the copr repo ? (or do we have the same problem as the fedora package has) ?

**Comment by kwizart** [comment]
Closing as won't fix, copr repo is still MIA.

Removing previous broken themes pending...
