### ISSUE TITLE
sacd_extract and dsf2flac

### ISSUE THREAD

**Issue by JerukPeras** [rpmfusion-infra/fedy#71]
** Please describe why this package is not eligible for Fedora ?**
Please mention why Fedora cannot package this component and which RPM Fusion section would apply "free, nonfree, rpi, cuda".

_Because Arch Linux available in the AUR.
I don't know maybe better to put in RPM Fusion?_

** Is this software redistributable ?**
If a proprietary software is there a notice that the component can be redistributed ?

_Yes_

** Is this software an alternate version of a Fedora provided package ?**
If the package already exists in Fedora, please mention why it is incomplete and if the fedora package is even relevant ?

_No_

**Additional context**

_This popular tools used/provide by SONORE as GUI [https://www.sonore.us/iso2dsd.html](url) and [https://www.sonore.us/dsd2flac.html](url)_

_Based:
[https://github.com/sacd-ripper/sacd-ripper](url) (Description: Extract DSD files from an SACD image) and...
[https://github.com/hank/dsf2flac](url) (Description: Tool for converting DSF to FLAC files)._

_But enhanced version available from [https://github.com/EuFlo/sacd-ripper](url) and [https://github.com/EuFlo/dsf2flac](url)_

**Comment by leigh123linux** [comment]
Both packages don't qualify for rpmfusion repo, try fedora repo instead.
