### ISSUE TITLE
Update Unifi Controller to the latest.

### ISSUE THREAD

**Issue by andrewm659** [rpmfusion-infra/fedy#73]
** Please describe why this package is not eligible for Fedora ?**
Please mention why Fedora cannot package this component and which RPM Fusion section would apply "free, nonfree, rpi, cuda".
This is software FROM Ubiquiti.  Made available on Debian/Ubuntu.  It just needs to be updated.

This is currently in the nonfree repo.

** Is this software redistributable ?**
It is already distributed via .deb package from Ubiquiti.

** Is this software an alternate version of a Fedora provided package ?**
If the package already exists in Fedora, please mention why it is incomplete and if the fedora package is even relevant ?
It does not exist in Fedora.

This package needs to be updated.  The latest version is 6.0.36 I believe.

**Comment by kwizart** [comment]
You need to use bugzilla.rpmfusion.org to get in touch to the unifi maintainer to have an update.
