### ISSUE TITLE
freerdp-freeworld

### ISSUE THREAD

**Issue by bllngr** [rpmfusion-infra/fedy#74]
**Please describe why this package is not eligible for Fedora ?**
FreeRDP can be built with FFMPEG for modern H264-AVC442 or AVC444 support. There's not much documentation, but IIUC, it basically must be built with the `WITH_FFMPEG=ON` flag (see their [spec file](https://github.com/FreeRDP/FreeRDP/blob/master/packaging/rpm/freerdp-nightly.spec#L120)). Fedora doesn't ship FFMPEG, so their FreeRDP package doesn't use it.

**Is this software redistributable ?**
Yes, `freerdp` itself is part of Fedora already, FFMPEG is part of `rpmfusion-free`.

**Is this software an alternate version of a Fedora provided package ?**
See above.

**Additional context**
There are official nightlies with FFMPEG for OpenSUSe available at http://pub.freerdp.com/repositories/rpm/opensuse/sl15.1/freerdp-nightly/x86_64/, but they link to an older version of FFMPEG than the one in `rpmfusion-free`, so they don't work on Fedora (33 at least).

**Comment by ValdikSS** [comment]
That would be very useful! No modifications of spec file required, everything is already included in Fedora's .spec, only need to activate ffmpeg support with a variable.

**Comment by MalteKiefer** [comment]
So to understand it correctly, we must build a new version with ffmpeg support?
Or is there already a copr for it?

**Comment by ValdikSS** [comment]
> So to understand it correctly, we must build a new version with ffmpeg support?
> Or is there already a copr for it?

I did not find a COPR, but there's everything ready in the official Fedora spec.

**Comment by kwizart** [comment]
With f39+ there will be ffmpeg support in the default fedora freerdp package.
