### ISSUE TITLE
ashmem and binder kernel modules

### ISSUE THREAD

**Issue by Rat-S** [rpmfusion-infra/fedy#80]
** Please describe why this package is not eligible for Fedora ?**
Please mention why Fedora cannot package this component and which RPM Fusion section would apply "free, nonfree, rpi, cuda". 
It appears that fedora believes these two modules aren't in good enough shape [to be packaged within fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1455411) . 

** Is this software redistributable ?**
If a proprietary software is there a notice that the component can be redistributed ?
Yes. These are someway related to the Linux kernel itself and are in same license. These modules are already available in Debian. 

** Is this software an alternate version of a Fedora provided package ?**
If the package already exists in Fedora, please mention why it is incomplete and if the fedora package is even relevant ? 
No. 

**Additional context**
These are required modules for running anbox in fedora, and there seems to be lot of interest in running anbox from within fedora.

**Comment by kwizart** [comment]
Thanks for the report.

Have you tried to raise this concern to the fedora kernel team ? as I understand, theses modules are from the staging directory.
Eventually having them enabled in fedora but distributed into a separate kernel-module package can be achieved...

**Comment by Rat-S** [comment]
Hi. 

> Have you tried to raise this concern to the fedora kernel team ? as I understand, theses modules are from the staging directory.


There's a request on redhat bugzilla pending for quite sometime. 

https://bugzilla.redhat.com/show_bug.cgi?id=1455411

Thank you.

**Comment by kwizart** [comment]
Waydroid is in fedora (without ashmem needs)...

Let's close this . (if you want to submit a separate plugin to have everything setup as appropriate, feel free...
