### ISSUE TITLE
Missing info on this project

### ISSUE THREAD

**Issue by mhsabbagh** [rpmfusion-infra/fedy#9]
Hello.

It sounds like the original Fedy maintainer stopped working on it and deleted his repo, and I've read that this repository has nothing to do with the original one.

This rises some questions that I hope you can address in your README:

- Are you going to use the same "Fedy" name instead of using a new name? I am asking this to avoid people mistaking you for the original Fedy maintainer.
- Are you going to maintain this tool from now on continuously for all the supported Fedora releases?
- Are you going to push this tool in the RPM Fusion repository or just use the Copr kwizart/fedy?

Thanks for your work.

**Comment by kwizart** [comment]
For information, the one who deleted the previous project was not the original maintainer.
I got in touch with the original maintainer rather early as soon as I get knowledge of the project.

There was discussion to have fedy in RPM Fusion, but some disagreed.
So far it's easier to maintain in a copr repository, specially as all the internal infra is already wired automatically between github/copr. So having it in copr versus rpmfusion proper is too much an implementation detail.

For me fedy should be a complement to software/yumex/dnfdragora application.
So it should handle well known and vendors repositories of packages

**Comment by mhsabbagh** [comment]
Thanks for the info. I hope you consider adding this info to your README because a lot of people seem to be lost on what happened to Fedy.

Regards.

**Comment by kwizart** [comment]
Is there any public discussion where this concern was raised ?

**Comment by mhsabbagh** [comment]
Ah yes:
https://www.reddit.com/r/Fedora/comments/cveq55/any_news_on_what_happened_to_fedy/

The main reason I even stumbled upon this repo was because of a comment on my article about Fedy: https://fosspost.org/tutorials/things-to-do-after-installing-fedora
