### ISSUE TITLE
akmod-r8168

### ISSUE THREAD

**Issue by tazihad** [rpmfusion-infra/fedy#91]
** Please describe why this package is not eligible for Fedora ?**
RPMFusion: nonfree
This package is proprietary driver.

** Is this software redistributable ?**
Yes, already distributed by several other linux distros including debian.

** Is this software an alternate version of a Fedora provided package ?**
No.

**Additional context**
r8169 driver is included with kernel. But it has bugs. Where r8168 driver works perfectly. There's ongoing bug that creates problem with r8169 driver would freeze system any kernel that is newer than 5.11+. Multiple issue has been [reported](https://bugzilla.redhat.com/show_bug.cgi?id=1914631 "reported").
Debian has [r8168-dkms](https://packages.debian.org/bullseye/r8168-dkms "r8168-dkms") package.
It's even available in [AUR](https://aur.archlinux.org/packages/r8168-dkms/ "AUR").
available in centos [package](https://centos.pkgs.org/7/elrepo-x86_64/kmod-r8168-8.049.02-1.el7_9.elrepo.x86_64.rpm.html)
I am asking for a **akmod-r8168** package so that I can install and use it in my Fedora Kinoit/Silverblue system. This r8169 bug also occurs in regular Fedora 35. Which causes system freezes.

**Comment by tazihad** [comment]
It's been 2 months. I beg to the devs. Please build it for me. I can't use fedora without it. My laptop wifi don't work without this driver.

**Comment by MPdaedalus** [comment]
I second this. the open source r8169 driver is garbage and has been for 10 years, I have to manually update r8168 driver on every kernel update, a rpmfusion package would be ideal.

**Comment by kwizart** [comment]
One has to volunteer to maintain this package in rpmfusion.
https://rpmfusion.org/Contribute
