### ISSUE TITLE
haruna

### ISSUE THREAD

**Issue by kah0922** [rpmfusion-infra/fedy#92]
** Please describe why this package is not eligible for Fedora ?**
Please mention why Fedora cannot package this component and which RPM Fusion section would apply "free, nonfree, rpi, cuda".
Haruna is a media player for KDE using libmpv. As mpv-libs is not included in the Fedora repos, Haruna cannot be packaged.

Section: Free
** Is this software redistributable ?**
If a proprietary software is there a notice that the component can be redistributed ?
Yes
** Is this software an alternate version of a Fedora provided package ?**
If the package already exists in Fedora, please mention why it is incomplete and if the fedora package is even relevant ?
No
**Additional context**
[https://invent.kde.org/multimedia/haruna](https://invent.kde.org/multimedia/haruna)

**Comment by kwizart** [comment]
Haruna is in fedora (at least f37+)
