### ISSUE TITLE
digikam-freeworld, with mediaplayer A/V (ffmpeg) support

### ISSUE THREAD

**Issue by pgnd** [rpmfusion-infra/fedy#94]
> Please describe why this package is not eligible for Fedora ?

digikam can be built with qtav/ffmpeg for audio/video mediaplayer support.

Fedora doesn't ship FFMPEG, so their digikam package doesn't use it.

> Is this software redistributable ?
> Is this software an alternate version of a Fedora provided package ?

yes & yes.

digikam is currently built for Fedora 35/36:

	https://src.fedoraproject.org/rpms/digikam

but, @ spec 

	https://src.fedoraproject.org/rpms/digikam/blob/rawhide/f/digikam.spec#_171

explicitly *DISABLES* mediaplayer support,

```
-DENABLE_MEDIAPLAYER:BOOL=OFF
```
required for video/audio thumbnail/player support

digikam's MEDIAPLAYER support requires

	https://www.digikam.org/api/#sourcedirs

optional deps of `libqtav` & `libffmpeg`

```
libqtav 	opt 	>= 1.12.0 	http://www.qtav.org 	To play video and audio (ENABLE_MEDIAPLAYER=on) 	
libffmpeg 	opt 	>= 3.3.x 	http://www.ffmpeg.org 	To play video and audio (ENABLE_MEDIAPLAYER=on), libavformat, libavutil, libavcodec used to extract video metadata  	
```

`ffmpeg` can't be packaged for Fedora official packages.

but is already available/installed
```
rpm -q --whatprovides /usr/lib64/{libavformat,libavutil,libavcodec,libQtAV}.so.* | uniq
	ffmpeg-libs-4.4.1-4.fc35.x86_64
	libqtav-1.13.0-11.fc35.x86_64
```

from
```
dnf info libqtav | grep "From repo"
	From repo    : rpmfusion-free
dnf info ffmpeg-libs | grep "From repo"
	From repo    : rpmfusion-free-updates
```

**Comment by leigh123linux** [comment]
ffmpeg is available in fedora repos.
