### ISSUE TITLE
font-mukti available from https://github.com/mitradranirban/fonts-mukti

### ISSUE THREAD

**Issue by mitradranirban** [rpmfusion-infra/fedy#95]
** Please describe why this package is not eligible for Fedora ?**
It is derived from MuktiNarrow font which was part of Fedora earlier but was removed in  as version 0.94 available then was distributed under GPL2 without the font exception clause. Current versions 2.1.2 is distributed with the font exception clause
Please mention why Fedora cannot package this component and which RPM Fusion section would apply "free, nonfree, rpi, cuda".
Fedora already ships with Lohit Bengali font which gives coverage for Bengali script so no one is willing to do additional work of adding another Bengali font.
It is to be distributed under "free" category as it is under GPL with font exception 
** Is this software redistributable ?**
If a proprietary software is there a notice that the component can be redistributed ?
Not applicable 
** Is this software an alternate version of a Fedora provided package ?**
No
If the package already exists in Fedora, please mention why it is incomplete and if the fedora package is even relevant ?
Not applicable 
**Additional context**

**Comment by leigh123linux** [comment]
Sorry this doesn't qualify for rpmfusion due to the free licence, file your request at fedora instead.
