### ISSUE TITLE
Requiring Gtk but it has 3 versions available; use imports.gi.versions to pick one

### ISSUE THREAD

**Issue by ShamimIslam** [rpmfusion-infra/fedy#96]
**Describe the bug**
Unable to start fedy

**To Reproduce**
1. install gtk4-4.4.2-1.fc35.x86_64
2. install gtk2-2.24.33-5.fc35.x86_64
3. gtk3-3.24.31-2.fc35.x86_64
4. Run fedy

**Expected behavior**
fedy runs

**Actual behavior**
Fedy crashes:

(gjs:1179114): Gtk-WARNING **: 20:36:57.563: Unknown key gtk-button-images in /home/shamim/.config/gtk-4.0/settings.ini

(gjs:1179114): Gtk-WARNING **: 20:36:57.563: Unknown key gtk-menu-images in /home/shamim/.config/gtk-4.0/settings.ini

(gjs:1179114): Gtk-WARNING **: 20:36:57.564: Unknown key gtk-toolbar-style in /home/shamim/.config/gtk-4.0/settings.ini

(gjs:1179114): Gjs-CRITICAL **: 20:36:58.486: JS ERROR: TypeError: Gtk.WindowPosition is undefined
_buildUI@./app.js:37:17
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
_onStartup@./app.js:76:14
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
@./app.js:720:17

(gjs:1179114): Gjs-CRITICAL **: 20:36:58.486: JS ERROR: TypeError: this._window is undefined
_onActivate@./app.js:70:9
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
@./app.js:720:17

**Version Information:**
Please run the following commands in the terminal and provide the output after the colon:
- `rpm -qi fedy`:
Name        : fedy
Version     : 4.8.0
Release     : 1.fc29
Architecture: noarch
Install Date: Wed 29 May 2019 08:19:49 PM EDT
Group       : System/Management
Size        : 555765
License     : GPLv3+
Signature   : (none)
Source RPM  : fedy-4.8.0-1.fc29.src.rpm
Build Date  : Wed 29 May 2019 09:25:59 AM EDT
Build Host  : a4268bc0c51d
URL         : https://www.folkswithhats.org/
Summary     : Install codecs and additional software
Description :
Fedy lets you install multimedia codecs and additional software that Fedora
doesn't want to ship, like mp3 support, Adobe Flash, Oracle Java etc., and
much more with just a few clicks.

- `rpm -E %fedora`:
35 
- `uname -a`:
Linux s55-c 5.16.11-200.fc35.x86_64 #1 SMP PREEMPT Wed Feb 23 17:08:49 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by ShamimIslam** [comment]
Please be advised, I upgraded from Fedora 27 all the way through to Fedora 35, and certain programs use gtk2, and others use gtk3. I did not manually install them. This laptop has been in service a long time.

**Comment by leigh123linux** [comment]
Try updating fedy, the current work ok.


```
$ rpm -q gtk3 gtk2 gtk4 fedy
gtk3-3.24.31-2.fc36.x86_64
gtk2-2.24.33-6.fc36.x86_64
gtk4-4.6.1-2.fc36.x86_64
fedy-5.0.20-1.fc36.noarch
```

**Comment by kwizart** [comment]
Fedy is available from https://copr.fedorainfracloud.org/coprs/kwizart/fedy/ nowadays.

**Comment by ShamimIslam** [comment]
Hi - I'm on Fedora 35, not Fedora 36. How do you propose I proceed?

**Comment by ShamimIslam** [comment]
You're on Fedora 36. Unfortunately "works for me" is not a valid response for Fedora 35. Thanks.

**Comment by ShamimIslam** [comment]
ls -al *kwizart*
-rw-r--r-- 1 root root 364 Mar  3 18:57 _copr:copr.fedorainfracloud.org:kwizart:fedy.repo

**Comment by ShamimIslam** [comment]
Correct response would have been: please upgrade to the latest fedy on Fedora 35. 
Your initial response made me think you were providing a Fedora 36 reponse.

**Comment by ShamimIslam** [comment]
P.S. Seeing as I *just* installed fedy 2 days ago, it wouldn't be unhelpful to indicate that the Fedora 35 version is now "5.0.20-1"

So long and thanks for all the fish.
