### ISSUE TITLE
hblock

### ISSUE THREAD

**Issue by chapters1000** [rpmfusion-infra/fedy#97]
** Please describe why this package is not eligible for Fedora ?**
Please mention why Fedora cannot package this component and which RPM Fusion section would apply "free, nonfree, rpi, cuda".
**I'm not sure**.

** Is this software redistributable ?**
If a proprietary software is there a notice that the component can be redistributed ?
**hectorm/hblock is licensed under the MIT License**

** Is this software an alternate version of a Fedora provided package ?**
If the package already exists in Fedora, please mention why it is incomplete and if the fedora package is even relevant ?
**I'm not sure**.

**Additional context**
**See**: https://github.com/hectorm/hblock

**Comment by leigh123linux** [comment]
This doesn't qualify for rpmfusion, file your request @fedora
