### ISSUE TITLE
intel-media-driver for RHEL/CentOS 9

### ISSUE THREAD

**Issue by loganmc10** [rpmfusion-infra/fedy#98]
intel-media-driver is already included in RPM Fusion for Fedora 34&35. CentOS 9 is based on Fedora 34, so I'm hoping we could get this package for RHEL/CentOS9

**Comment by kwizart** [comment]
This is not a fedy issue. Package branch request should be directed to the maintainer. 
intel-media-driver will be made for epel9 at it's own pace.
